version: "3"

services:
  api:
    build: .
    depends_on:
      - api_db
    expose:
      - 8007
    environment:
      DATABASE_URL: postgres://postgres:postgres@api_db/postgres

  other-service:
    build: .
    depends_on:
      - api_db
    expose:
      - 8007
    environment:
      DATABASE_URL: postgres://postgres:postgres@api_db/postgres

  api_db:
    image: postgres:11.2-alpine

  web-app:
    build: ./web-app
    volumes:
      - web-app-build:/app/build
    expose:
      - 3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-app-build:/web-app-build
    ports:
      - 80:80
    depends_on:
      - api
      - web-app

volumes:
  web-app-build:
